// rtc-mode/clients/web/src/App.tsx
import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import {
  AvatarManager,
  AvatarSDK,
  AvatarView,
  DrivingServiceMode,
  Environment,
} from '@spatialwalk/avatarkit'
import { AvatarPlayer, LiveKitProvider } from '@spatialwalk/avatarkit-rtc'

type TokenResponse = {
  token: string
  url: string
  room: string
  identity: string
}

const appId = import.meta.env.VITE_SPATIALREAL_APP_ID
const avatarId = import.meta.env.VITE_SPATIALREAL_AVATAR_ID
const sessionToken = import.meta.env.VITE_SPATIALREAL_SESSION_TOKEN

function App() {
  const stageRef = useRef<HTMLDivElement | null>(null)
  const viewRef = useRef<AvatarView | null>(null)
  const playerRef = useRef<AvatarPlayer | null>(null)

  const [roomName, setRoomName] = useState('pure-rtc-room')
  const [identity, setIdentity] = useState('')
  const [connected, setConnected] = useState(false)
  const [connecting, setConnecting] = useState(false)
  const [logs, setLogs] = useState<string[]>([])

  const canConnect = useMemo(() => {
    return !connecting && !connected && Boolean(appId) && Boolean(avatarId)
  }, [connecting, connected])

  const pushLog = useCallback((message: string) => {
    setLogs((prev) => [`${new Date().toLocaleTimeString()} ${message}`, ...prev].slice(0, 30))
  }, [])

  const requestToken = useCallback(async (): Promise<TokenResponse> => {
    const response = await fetch('/token', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ room: roomName, identity }),
    })

    if (!response.ok) {
      throw new Error(await response.text())
    }

    return response.json()
  }, [roomName, identity])

  const disconnect = useCallback(async () => {
    try {
      if (playerRef.current) {
        await playerRef.current.disconnect()
      }
    } catch (error) {
      pushLog(`Disconnect failed: ${(error as Error).message}`)
    }

    try {
      viewRef.current?.dispose?.()
    } catch {
      // ignore dispose errors
    }

    playerRef.current = null
    viewRef.current = null
    setConnected(false)
  }, [pushLog])

  const connect = useCallback(async () => {
    if (!canConnect || !stageRef.current) {
      return
    }

    setConnecting(true)
    pushLog('Preparing Pure RTC connection...')

    try {
      const token = await requestToken()

      if (!AvatarSDK.isInitialized) {
        await AvatarSDK.initialize(appId, {
          environment: Environment.intl,
          drivingServiceMode: DrivingServiceMode.host,
        })
      }

      if (sessionToken) {
        AvatarSDK.setSessionToken?.(sessionToken)
      }

      const manager = AvatarManager.shared
      if (!manager) {
        throw new Error('AvatarManager unavailable')
      }

      const avatar = await manager.load(avatarId)
      const view = new AvatarView(avatar, stageRef.current)
      viewRef.current = view

      const provider = new LiveKitProvider()
      const player = new AvatarPlayer(provider as any, view, { logLevel: 'info' })
      playerRef.current = player

      await player.connect({
        url: token.url,
        token: token.token,
        roomName: token.room,
      })

      await player.startPublishing()
      setConnected(true)
      pushLog(`Connected to room: ${token.room} (${token.identity})`)
      pushLog('This is a pure RTC sample without agent dispatch')
    } catch (error) {
      pushLog(`Connection failed: ${(error as Error).message}`)
      await disconnect()
    } finally {
      setConnecting(false)
    }
  }, [canConnect, disconnect, pushLog, requestToken])

  useEffect(() => {
    return () => {
      void disconnect()
    }
  }, [disconnect])

  return (
    <div className="pure-shell">
      <header className="pure-header">
        <div>
          <p className="eyebrow">RTC Mode</p>
          <h1>LiveKit Pure RTC Console</h1>
        </div>
        <span className={`state ${connected ? 'ok' : 'idle'}`}>{connected ? 'Connected' : connecting ? 'Connecting' : 'Disconnected'}</span>
      </header>

      <main className="pure-grid">
        <section className="card controls">
          <h2>Session settings</h2>
          <p>Validates room connectivity and real-time path only, without Agent plugin.</p>

          <label htmlFor="room">Room name</label>
          <input
            id="room"
            value={roomName}
            onChange={(event) => setRoomName(event.target.value)}
            placeholder="pure-rtc-room"
          />

          <label htmlFor="identity">User identity (optional)</label>
          <input
            id="identity"
            value={identity}
            onChange={(event) => setIdentity(event.target.value)}
            placeholder="browser-dev"
          />

          <div className="actions">
            <button disabled={!canConnect} onClick={() => void connect()}>
              {connecting ? 'Connecting...' : 'Connect RTC'}
            </button>
            <button className="ghost" disabled={!connected && !connecting} onClick={() => void disconnect()}>
              Disconnect
            </button>
          </div>

          <dl>
            <dt>App ID</dt>
            <dd>{appId || 'Not configured'}</dd>
            <dt>Avatar ID</dt>
            <dd>{avatarId || 'Not configured'}</dd>
            <dt>LiveKit Client</dt>
            <dd>2.16.1</dd>
          </dl>
        </section>

        <section className="card stage-wrap">
          <h2>Avatar Stage</h2>
          <div className="stage" ref={stageRef} />
        </section>

        <section className="card logs">
          <h2>Runtime logs</h2>
          <ul>
            {logs.length === 0 && <li>Waiting for actions...</li>}
            {logs.map((line, index) => (
              <li key={`${line}-${index}`}>{line}</li>
            ))}
          </ul>
        </section>
      </main>
    </div>
  )
}

export default App

// spatialreal-agent-quickstart/frontend/src/App.vue
<script setup lang="ts">
import { nextTick, onBeforeUnmount, ref } from 'vue'
import { Room } from 'livekit-client'
import {
  AvatarManager,
  AvatarSDK,
  AvatarView,
  DrivingServiceMode,
  Environment,
} from '@spatialwalk/avatarkit'
import { AvatarPlayer, LiveKitProvider } from '@spatialwalk/avatarkit-rtc'

const container = ref<HTMLDivElement | null>(null)
const status = ref('Click Connect to start')
const connecting = ref(false)
const connected = ref(false)
const micOn = ref(false)

let avatarView: AvatarView | null = null
let player: AvatarPlayer | null = null
let roomClient: Room | null = null

async function connect(): Promise<void> {
  if (connecting.value || connected.value) return
  connecting.value = true
  status.value = 'Requesting token...'

  try {
    const response = await fetch(import.meta.env.VITE_TOKEN_ENDPOINT || '/token', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ room: 'voice-agent-room' }),
    })
    if (!response.ok) throw new Error('Failed to fetch token')

    const { token, url, room } = await response.json()

    if (!AvatarSDK.isInitialized) {
      await AvatarSDK.initialize(import.meta.env.VITE_SPATIALREAL_APP_ID, {
        environment: Environment.intl,
        drivingServiceMode: DrivingServiceMode.host,
      })
    }

    await nextTick()
    const mountEl = container.value
    if (!mountEl) throw new Error('Avatar container is not ready')

    await player?.disconnect().catch(() => undefined)
    avatarView?.dispose()

    const avatar = await AvatarManager.shared.load(import.meta.env.VITE_SPATIALREAL_AVATAR_ID)
    avatarView = new AvatarView(avatar, mountEl)
    player = new AvatarPlayer(new LiveKitProvider(), avatarView)

    status.value = 'Connecting to LiveKit...'
    await player.connect({ url, token, roomName: room })
    roomClient = player.getNativeClient() as Room
    if (!roomClient) throw new Error('LiveKit room client is unavailable')

    await roomClient.startAudio()

    connected.value = true
    status.value = 'Connected. Click Start Mic to talk.'
  } catch (error) {
    status.value = error instanceof Error ? error.message : 'Connection failed'
  } finally {
    connecting.value = false
  }
}

async function startMic(): Promise<void> {
  if (!player || micOn.value) return

  status.value = 'Starting microphone...'
  try {
    await player.startPublishing()
    micOn.value = true
    status.value = 'Mic is on. Start speaking.'
  } catch (error) {
    status.value =
      error instanceof Error
        ? `Failed to start microphone: ${error.message}`
        : 'Failed to start microphone.'
  }
}

async function stopMic(): Promise<void> {
  if (!micOn.value) return
  await player?.stopPublishing().catch(() => undefined)
  micOn.value = false
  status.value = 'Mic is off.'
}

async function disconnect(): Promise<void> {
  await stopMic()
  await player?.disconnect().catch(() => undefined)
  avatarView?.dispose()
  player = null
  avatarView = null
  roomClient = null
  connected.value = false
  status.value = 'Disconnected'
}

async function toggleConnection(): Promise<void> {
  if (connecting.value) return
  if (connected.value) {
    await disconnect()
    return
  }
  await connect()
}

async function toggleMic(): Promise<void> {
  if (!connected.value || connecting.value) return
  if (micOn.value) {
    await stopMic()
    return
  }
  await startMic()
}

onBeforeUnmount(async () => {
  await disconnect()
})
</script>

<template>
  <div style="min-height:100vh; display:flex; align-items:center; justify-content:center; padding:16px;">
    <div style="width:min(720px, 100%); display:flex; flex-direction:column; gap:10px;">
      <div
        ref="container"
        style="width:100%; aspect-ratio:16/10; min-height:320px; border-radius:12px; overflow:hidden; border:1px solid;"
      />

      <div style="display:flex; gap:8px; flex-wrap:wrap;">
        <button :disabled="connecting" @click="toggleConnection">
          {{ connecting ? 'Connecting...' : connected ? 'Disconnect' : 'Connect' }}
        </button>
        <button :disabled="!connected || connecting" @click="toggleMic">
          {{ micOn ? 'Stop Mic' : 'Start Mic' }}
        </button>
      </div>

      <div style="font-size:14px;">{{ status }}</div>
    </div>
  </div>
</template>
